select * from customer;

--Q1 What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

--Q2 which customers used discount but still spend more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--Q3 Which are the top 5 products with highest average rating?
select item_purchased,round(avg(review_rating::numeric),2) as "Average Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4 Compare the average Purchase amounts between Standard and Express Shipping?
select shipping_type,round(avg(purchase_amount),2) as "Average Purchase"
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

--Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non subscriber?
select subscription_status,count(*) as customer_count,avg(purchase_amount) as avg_purchase,sum(purchase_amount) as avg_total
from customer
group by subscription_status
order by avg_purchase, avg_total desc;